/**
 * Preview Service
 *
 * Stores and retrieves temporary preview packages uploaded via `apex preview --upload`.
 * Each package expires after 24 hours and the file is deleted on expiry.
 */

import { eq, lt } from 'drizzle-orm';
import { nanoid } from 'nanoid';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { getDatabase, previewPackages } from '../db';

const TTL_MS = 24 * 60 * 60 * 1000; // 24 hours

/**
 * Returns the directory where preview .map files are stored.
 * Mirrors `config.storagePath` but under a `previews/` sibling folder.
 */
function previewDir(storagePath: string): string {
  return path.join(path.dirname(storagePath), 'previews');
}

/**
 * Store a preview package uploaded from the CLI.
 *
 * @param token    Preview token generated by the CLI
 * @param appId    Reverse-domain app identifier
 * @param buffer   Raw bytes of the .map file
 * @param storagePath  Base storage path from server config
 * @param developerId  Optional authenticated developer ID
 * @returns        The stored preview record
 */
export async function storePreview(
  token: string,
  appId: string,
  buffer: Buffer,
  storagePath: string,
  developerId?: string,
) {
  const db = getDatabase();

  // Validate token format (basic sanity — prevents path traversal)
  if (!/^[a-zA-Z0-9._-]{1,200}$/.test(token)) {
    throw Object.assign(new Error('Invalid preview token format'), { statusCode: 400 });
  }

  // Remove any existing preview with the same token
  const [existing] = await db
    .select()
    .from(previewPackages)
    .where(eq(previewPackages.token, token))
    .limit(1);
  if (existing) {
    try { fs.unlinkSync(existing.packagePath); } catch { /* already gone */ }
    await db.delete(previewPackages).where(eq(previewPackages.token, token));
  }

  // Write file to disk
  const dir = previewDir(storagePath);
  fs.mkdirSync(dir, { recursive: true });
  const packagePath = path.join(dir, `${token}.map`);
  fs.writeFileSync(packagePath, buffer);

  // Persist record
  const now = new Date();
  const record = {
    id: nanoid(),
    token,
    appId,
    developerId: developerId ?? null,
    packagePath,
    expiresAt: new Date(now.getTime() + TTL_MS),
    createdAt: now,
  };
  await db.insert(previewPackages).values(record);
  return record;
}

/**
 * Look up a preview record by token, returning null if missing or expired.
 */
export async function getPreview(token: string) {
  const db = getDatabase();
  const [record] = await db
    .select()
    .from(previewPackages)
    .where(eq(previewPackages.token, token))
    .limit(1);
  if (!record) return null;
  if (record.expiresAt && record.expiresAt.getTime() < Date.now()) {
    await deletePreview(token);
    return null;
  }
  return record;
}

/**
 * Delete a preview by token (removes DB row + file).
 */
export async function deletePreview(token: string) {
  const db = getDatabase();
  const [record] = await db
    .select()
    .from(previewPackages)
    .where(eq(previewPackages.token, token))
    .limit(1);
  if (record) {
    try { fs.unlinkSync(record.packagePath); } catch { /* already gone */ }
    await db.delete(previewPackages).where(eq(previewPackages.token, token));
  }
}

/**
 * Purge all expired preview packages (call periodically).
 */
export async function purgeExpiredPreviews() {
  const db = getDatabase();
  const expired = await db
    .select()
    .from(previewPackages)
    .where(lt(previewPackages.expiresAt, new Date()));
  for (const record of expired) {
    try { fs.unlinkSync(record.packagePath); } catch { /* already gone */ }
  }
  if (expired.length > 0) {
    await db
      .delete(previewPackages)
      .where(lt(previewPackages.expiresAt, new Date()));
  }
  return expired.length;
}
